spring.application.name=Desafiocnpj

spring.config.import=optional:classpath:application-local.properties
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/cnpj}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true